services:
  db:
    image: mysql
    container_name: db_data
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: hospital
    volumes:
      - local_mysql:/var/lib/mysql
    ports:
      - "3307:3306"
    networks:
      - mysql-phpmyadmin

  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin
    environment:
      PMA_HOST: db
    ports:
      - "80:80"
    networks:
      - mysql-phpmyadmin


volumes:
  local_mysql:

networks:
  mysql-phpmyadmin:

